@baseUrl = http://localhost
@email = email@gmail.com
@password = mypassword
###

POST {{baseUrl}}:3000/users/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
POST {{baseUrl}}:3000/users
Content-Type: application/json

{
  "name": "myuser",
  "password": "{{password}}",
  "email": "{{email}}",
  "birthDate": "1999-01-01",
  "address": {
    "country": "BR",
    "state": "SP",
    "street": "Fake Street",
    "number": 23
  }
}
